In [1]:
import torch

In [2]:
import numpy as np

### torch 基本处理单元

In [3]:
# 返回的数组大小5x4的矩阵
torch.Tensor(5, 4)

tensor([[ 0.0000e+00, -2.0000e+00,  0.0000e+00, -2.0000e+00],
        [ 1.3382e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.4013e-45,  1.8754e+28,  2.5382e-09],
        [ 1.0622e-05,  1.0254e-11,  2.6610e+23,  1.3002e+22],
        [ 2.6584e+23,  2.5202e-09,  8.5764e-07,  8.4274e-07]])

In [4]:
# 返回的数组大小是5x4的矩阵，初始化是0~1的均匀分布
torch.rand(5, 4)

tensor([[0.2612, 0.9870, 0.5477, 0.2493],
        [0.9043, 0.0477, 0.8788, 0.8793],
        [0.5501, 0.6282, 0.4119, 0.1462],
        [0.9821, 0.4173, 0.0282, 0.3880],
        [0.6697, 0.1608, 0.0459, 0.8412]])

In [5]:
# 得到矩阵大小
a = torch.rand(5, 4)
a.size()

torch.Size([5, 4])

In [6]:
# numpy 类似的返回5x4大小的矩阵
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# numpy 和 torch.Tensor 之间的转换
a = torch.rand(5, 4)
b = a.numpy()
print(b)

[[0.41055548 0.4136678  0.40775907 0.9686778 ]
 [0.7950482  0.7650699  0.29611808 0.39977098]
 [0.42218822 0.64974487 0.46897334 0.4514438 ]
 [0.33382428 0.46113443 0.16800797 0.26376712]
 [0.50063115 0.18332887 0.02761292 0.97288346]]


In [8]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [3, 6]])


运算和numpy类似

In [9]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3

In [10]:
print(c * x)

tensor([[1.5380, 2.1645, 1.9965, 0.6107],
        [0.1352, 0.2802, 0.2215, 2.1290],
        [0.7199, 2.0720, 1.6724, 1.5550],
        [2.5734, 2.1738, 0.6306, 0.3496],
        [1.2427, 2.8435, 2.2669, 2.9603]])


In [11]:
print(x + y)

tensor([[0.7369, 1.6857, 1.2191, 1.0406],
        [0.7679, 0.4625, 0.4107, 0.7288],
        [0.3484, 1.6693, 1.4730, 0.7803],
        [1.4851, 1.0354, 0.9635, 0.2558],
        [1.0880, 1.4950, 1.0006, 1.5575]])


In [12]:
print(x.add(y))

tensor([[0.7369, 1.6857, 1.2191, 1.0406],
        [0.7679, 0.4625, 0.4107, 0.7288],
        [0.3484, 1.6693, 1.4730, 0.7803],
        [1.4851, 1.0354, 0.9635, 0.2558],
        [1.0880, 1.4950, 1.0006, 1.5575]])


In [13]:
# 可以直接进行操作改变原对象，x+y或者x.add()并不会改变x，但是x.add_()则会对x进行改变
x.add_(y)

tensor([[0.7369, 1.6857, 1.2191, 1.0406],
        [0.7679, 0.4625, 0.4107, 0.7288],
        [0.3484, 1.6693, 1.4730, 0.7803],
        [1.4851, 1.0354, 0.9635, 0.2558],
        [1.0880, 1.4950, 1.0006, 1.5575]])

In [14]:
print(x)

tensor([[0.7369, 1.6857, 1.2191, 1.0406],
        [0.7679, 0.4625, 0.4107, 0.7288],
        [0.3484, 1.6693, 1.4730, 0.7803],
        [1.4851, 1.0354, 0.9635, 0.2558],
        [1.0880, 1.4950, 1.0006, 1.5575]])


将 torch.Tensor 放到 GPU 上

In [15]:
# 判断一下电脑是否支持GPU
torch.cuda.is_available()

False

In [16]:
a = torch.rand(5, 4)
a = a.cuda()
print(a)

AssertionError: Torch not compiled with CUDA enabled

### torch 的自动求导功能
torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是torch.autograd.Variable

本质上Variable和Tensor没有什么区别，不过Variable会放在一个计算图里面，可以进行前向传播和反向传播以及求导  

![1.png](http://upload-images.jianshu.io/upload_images/3623720-1c2694b72e0341ce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

里面的creator表示通过什么操作得到的这个Variable，grad表示反向传播的梯度

In [ ]:
from torch.autograd import Variable

In [ ]:
# requires_grad 表示是否对其求梯度，默认是False
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [ ]:
# 对 x 和 y 分别求导
z.backward()

In [ ]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: 
 2
[torch.FloatTensor of size 1]

dz/dy: 
 1
[torch.FloatTensor of size 1]



### 神经网络部分

所依赖的主要是 torch.nn 和 torch.nn.functional

torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次

torch.nn.functional 表示的是直接对其做一次向前运算操作

In [ ]:
from torch import nn
import torch.nn.functional as F

In [ ]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out